import ATC from './actionTypeCreator'

export default {
    TOGGLE_SIDE_NAV: ATC("TOGGLE_SIDE_NAV"),
    UPDATE_VIS_STATUS:ATC("UPDATE_VIS_STATUS"),
    UPDATE_NAV_WINDOW:ATC("UPDATE_NAV_WINDOW"),
    UPDATE_NAV_ART :ATC("UPDATE_NAV_ART")

}