
import ATC from './actionTypeCreator'

export default {
    UPDATE_USER: ATC("UPDATE_USER"),
    UPDATE_USER_LOGGEDIN:ATC("UPDATE_USER_LOGGEDIN"),
    LOGIN_USER:ATC("LOGIN_USER"),
    VARIFY_JWT:ATC("VARIFY_JWT"),
    UPDATE_PASSWORD :ATC("UPDATE_PASSWORD"),
    LOGOUT:ATC("LOGOUT"),
    CREATE_USER:ATC("CREATE_USER")
}